# This notebook contains:
## 01. Import libraries and data
## 02. Merge rent data with state population data
## 03. Merge rent/state pop data with district pop data

# 01. Import libraries and data

In [1]:
# import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# create shortcut for data imports
path = r'C:\Users\jacym\Desktop\Career Foundry projects\german rent'

In [3]:
# state population data
df_pop = pd.read_csv(os.path.join(path, '02 data', 'original data', 'state_pop.csv'), index_col = False)

In [4]:
df_pop.head()

,state,population,surface area,population density,space/person,people/apt,population trend,pop trend cat
0,Baden_Württemberg,11090990,35751,310,42.55,2.21,0.26,increase
1,Bayern,13113880,70552,186,44.28,2.15,0.35,increase
2,Berlin,3659468,892,4103,38.66,1.85,0.39,increase
3,Brandenburg,2521627,29486,86,40.76,2.00,-0.12,decrease
4,Bremen,681439,419,1626,40.81,1.92,0.11,increase

In [5]:
df_pop.shape

(16, 8)

In [6]:
# district population data
df_district_pop = pd.read_csv(os.path.join(path, '02 data', 'cleaned data', 'district_pop.csv'), index_col = False)

In [7]:
df_district_pop.head()

                    regio2  districtPopTrend  districtPop
0                   Aachen              0.35       555465
1             Aachen_Kreis              0.35       555465
2          Ahrweiler_Kreis              0.18       129727
3  Aichach_Friedberg_Kreis              0.75       133596
4          Alb_Donau_Kreis              0.83       196047

In [8]:
# rent data
df_rent = pd.read_csv(os.path.join(path, '02 data', 'cleaned data', 'rent_cleaned.csv'), index_col = False)

In [9]:
df_rent.shape

(268772, 31)

In [10]:
df_rent.head(50)

,regio1,baseRent,totalRent,pricetrend,livingSpace,geo_plz,picturecount,newlyConst,yearConstructed,scoutId,...,garden,baseRentRange,noRoomsRange,livingSpaceRange,yearConstructedRange,regio2,regio3,description,date,price/unit
0,Nordrhein_Westfalen,595.00,840.00,4.62,86.00,44269,6,False,1965.0,96107057,...,True,4,4,4,2.0,Dortmund,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,2019-05-10,9.767442
1,Rheinland_Pfalz,800.00,NaN,3.47,89.00,67459,8,False,1871.0,111378734,...,False,5,3,4,1.0,Rhein_Pfalz_Kreis,Böhl_Iggelheim,Alles neu macht der Mai – so kann es auch für ...,2019-05-10,NaN
2,Sachsen,965.00,1300.00,2.72,83.80,1097,8,True,2019.0,113147523,...,False,6,3,4,9.0,Dresden,Äußere_Neustadt_Antonstadt,Der Neubau entsteht im Herzen der Dresdner Neu...,2019-10-08,15.513126
3,Sachsen,343.00,NaN,1.53,58.15,9599,9,False,1964.0,108890903,...,False,2,3,2,2.0,Mittelsachsen_Kreis,Freiberg,Abseits von Lärm und Abgasen in Ihre neue Wohn...,2019-05-10,NaN
4,Bremen,765.00,903.00,2.46,84.97,28213,19,False,1950.0,114751222,...,False,5,3,4,1.0,Bremen,Neu_Schwachhausen,Es handelt sich hier um ein saniertes Mehrfami...,2020-02-01,10.627280
5,Schleswig_Holstein,315.20,NaN,4.48,53.43,24891,5,False,1999.0,115531145,...,False,2,2,2,5.0,Schleswig_Flensburg_Kreis,Struxdorf,NaN,2020-02-01,NaN
6,Sachsen,310.00,380.00,1.01,62.00,9599,9,False,NaN,114391930,...,True,2,2,3,NaN,Mittelsachsen_Kreis,Freiberg,Am Bahnhof 14 in Freiberg\nHeizkosten und Warm...,2020-02-01,6.129032
7,Bremen,452.25,584.25,1.89,60.30,28717,5,False,1959.0,115270775,...,False,3,3,2,2.0,Bremen,St._Magnus,+ Komfortabler Bodenbelag: Die Wohnung ist zus...,2020-02-01,9.689055
8,Baden_Württemberg,580.00,690.00,3.77,53.00,79211,5,False,1970.0,106416361,...,False,4,2,2,2.0,Emmendingen_Kreis,Denzlingen,"Diese ansprechende, lichtdurchflutete DG-Wohnu...",2020-02-01,13.018868
9,Nordrhein_Westfalen,300.00,NaN,1.92,60.00,45888,7,False,1953.0,91383597,...,False,1,2,2,2.0,Gelsenkirchen,Bulmke_Hüllen,Sie sind auf der Suche nach einer gepflegten u...,2019-10-08,NaN
10,Sachsen,219.00,307.00,0.21,40.20,9130,11,False,1930.0,112923517,...,False,1,2,1,1.0,Chemnitz,Sonnenberg,Gemütliche 2-Raum Wohnung in Chemnitz. komple...,2019-10-08,7.636816
11,Sachsen,400.00,555.00,0.98,80.00,9669,9,False,1892.0,109842225,...,True,2,3,3,1.0,Mittelsachsen_Kreis,Frankenberg/Sachsen,Gern möchten wir Ihnen diese 3-Zimmer-Wohnung ...,2019-05-10,6.937500
12,Rheinland_Pfalz,650.00,920.00,2.77,100.00,76833,4,False,1912.0,111251778,...,True,5,4,4,1.0,Südliche_Weinstraße_Kreis,Frankweiler,Altes Sandsteinhaus unter Denkmalschutz im Jug...,2019-05-10,9.200000
13,Nordrhein_Westfalen,950.00,1150.00,3.45,123.44,59065,3,False,1951.0,101730329,...,False,6,4,6,2.0,Hamm,Mitte,Die angebotene Wohnfläche befindet sich im dri...,2019-10-08,9.316267
14,Nordrhein_Westfalen,972.60,1320.65,3.76,87.00,44229,12,True,2018.0,92798563,...,False,6,3,4,9.0,Dortmund,Kirchhörde,Der attraktive Neubau mit 10 Wohnungen liegt i...,2019-05-10,15.179885
15,Thüringen,220.00,300.00,1.67,36.63,99427,5,False,1990.0,106896167,...,False,1,1,1,4.0,Weimar,Schöndorf,Schönes fünfgeschossiges Mehrfamilienhaus in ...,2018-09-22,8.190008
16,Hessen,750.00,970.00,3.85,87.00,63452,17,False,NaN,93522345,...,False,5,3,4,NaN,Main_Kinzig_Kreis,Hanau,Schöne 3 Zimmer Whg.87qm (4WE) in ruhiger Wohn...,2019-10-08,11.149425
17,Sachsen,200.00,325.00,1.96,50.00,4720,12,False,1897.0,107018003,...,True,1,2,2,1.0,Mittelsachsen_Kreis,Döbeln,Vermietet wird eine gemütliche Wohnung mit zwe...,2018-09-22,6.500000
18,Nordrhein_Westfalen,329.00,NaN,3.12,65.00,47166,5,False,1914.0,111227157,...,False,2,2,3,1.0,Duisburg,Obermarxloh,Gepflegtes Mehrfamilienhaus in Duisburg-Oberm...,2019-05-10,NaN
19,Niedersachsen,1343.48,1878.48,2.35,127.95,37073,35,False,2013.0,113019528,...,False,7,5,6,8.0,Göttingen_Kreis,Göttingen,Im Südgebäude des Quartiers am Leinebogen ents...,2019-10-08,14.681360
20,Schleswig_Holstein,1150.00,1450.00,5.00,160.00,24539,15,False,1978.0,110416311,...,True,7,4,7,3.0,Neumünster,Wittorf,"Ihre repräsentative, großzügige und helle Wohn...",2019-10-08,9.062500
21,Baden_Württemberg,1190.00,1190.00,5.63,29.00,70376,13,False,NaN,113836264,...,False,7,1,1,NaN,Stuttgart,Bad_Cannstatt,Helle 3-Zimmer-Wohnung mit Galerie in Bad Cann...,2019-10-08,41.034483
22,Sachsen,1600.00,1946.00,5.34,140.00,4229,22,False,NaN,111412293,...,True,8,4,6,NaN,Leipzig,Lindenau,Umgeben von neu sanierten Indurstriedenkmalen ...,2019-10-08,13.900000
23,Bayern,1850.00,2030.00,4.47,81.00,80331,18,False,1871.0,113626688,...,False,8,2,4,1.0,München,Altstadt,Die Wohnung (OHNE Balkon !!) liegt im 4. OG (O...,2019-10-08,25.061728
24,Hamburg,620.00,760.00,6.30,55.89,22111,9,False,1953.0,111337159,...,False,5,3,2,2.0,Hamburg,Horn,Freuen Sie sich auf diese grundsanierte Wohnun...,2019-05-10,13.598139
25,Niedersachsen,316.00,396.00,0.59,31.00,38118,7,False,1890.0,115506913,...,False,2,1,1,1.0,Braunschweig,Westliches_Ringgebiet,"1,5 Zimmerwohnung im DG eines gepflegten Mehrf...",2020-02-01,12.774194
26,Baden_Württemberg,335.00,355.00,4.65,12.00,72622,7,False,1902.0,115403430,...,False,2,1,1,1.0,Esslingen_Kreis,Nürtingen,Das im März 2014 komplett renovierte Doppelhau...,2020-02-01,29.583333
27,Sachsen_Anhalt,300.30,447.62,1.08,56.66,39128,14,False,1977.0,114132653,...,False,1,3,2,3.0,Magdeburg,Kannenstieg,Das Objekt ist ruhig und grün gelegen. Der Auf...,2020-02-01,7.900106
28,Bayern,2400.00,2400.00,7.53,61.00,80804,25,False,1956.0,111398027,...,False,9,3,3,2.0,München,Schwabing_West,"Highlights:\n\n * alle Wände der Wohnräume, Kü...",2019-05-10,39.344262
29,Mecklenburg_Vorpommern,520.08,624.10,3.72,47.28,19055,13,True,2018.0,111018701,...,False,4,2,2,9.0,Schwerin,Paulsstadt,Auf www.residenzen-pfaffenteich.de sehen Sie d...,2019-05-10,13.200085
30,Bayern,800.00,970.00,6.49,106.08,94036,15,False,1974.0,105494876,...,False,5,2,5,3.0,Passau,Haidenhof_Süd,WOHNEN UND ENTSPANNEN!\n \nDie Architektur bei...,2018-09-22,9.144042
31,Nordrhein_Westfalen,315.18,445.18,3.90,60.00,40699,14,False,1976.0,107002234,...,True,2,2,2,3.0,Mettmann_Kreis,Erkrath,Zur Anmietung dieser Wohnung benötigen Sie zwi...,2018-09-22,7.419667
32,Bayern,2780.00,2780.00,6.08,100.00,80809,29,False,2016.0,112411856,...,False,9,3,4,9.0,München,Milbertshofen,Bitte beachten Sie: Die Wohnung ist komplett m...,2020-02-01,27.800000
33,Sachsen,165.00,245.00,1.94,35.00,8468,4,False,1914.0,113322419,...,False,1,2,1,1.0,Vogtlandkreis,Reichenbach_im_Vogtland,Helle 2-Raum-/Single-Wohnung in Hochpaterre mi...,2019-10-08,7.000000
34,Hessen,935.00,1195.00,5.22,35.00,65479,15,False,2013.0,93735747,...,False,6,1,1,8.0,Groß_Gerau_Kreis,Raunheim,"Wir bieten folgende neue, moderne und möbliert...",2019-10-08,34.142857
35,Sachsen,408.00,548.00,1.64,58.22,1705,14,False,1996.0,84094659,...,False,3,2,2,5.0,Sächsische_Schweiz_Osterzgebirge_Kreis,Freital,"Moderne, komfortable Wohnanlage mit Blick in d...",2019-05-10,9.412573
36,Sachsen,406.00,546.00,2.10,74.00,2708,9,False,1966.0,111185200,...,False,3,3,3,2.0,Görlitz_Kreis,Löbau,- modernes Bad mit Wanne und Dusche\n- große K...,2019-05-10,7.378378
37,Nordrhein_Westfalen,250.00,350.00,3.80,36.00,51427,5,False,NaN,113850656,...,False,1,1,1,NaN,Rheinisch_Bergischer_Kreis,Bergisch_Gladbach,"Im Untergeschoß gelegene kleine Wohnung, mit v...",2019-10-08,9.722222
38,Nordrhein_Westfalen,400.00,570.00,3.13,70.00,45329,6,False,NaN,113061748,...,False,2,3,3,NaN,Essen,Altenessen_Nord,"Nachmieter für eine gepflegte 3,5-Raum-Wohnung...",2019-10-08,8.142857
39,Sachsen,246.00,NaN,0.74,43.93,1589,9,False,1928.0,113998693,...,True,1,2,2,1.0,Meißen_Kreis,Riesa,Im Erdgeschoss wird Ihnen diese 2 Zimmerwohnun...,2020-02-01,NaN
40,Baden_Württemberg,850.00,1115.00,4.82,100.00,68309,10,False,NaN,56883893,...,False,6,3,4,NaN,Mannheim,Käfertal,Zum 01.08.2019 eventuell auch früher.\nZiehen ...,2019-05-10,11.150000
41,Niedersachsen,333.20,NaN,1.82,70.04,26919,2,False,1974.0,107366896,...,False,2,3,3,3.0,Wesermarsch_Kreis,Brake_Unterweser,NaN,2018-09-22,NaN
42,Nordrhein_Westfalen,553.98,753.98,3.70,87.33,59759,8,False,1994.0,102534814,...,True,4,3,4,5.0,Hochsauerlandkreis,Arnsberg,"Großzügiger Wohn/Essbereich (29,27 qm),weiße E...",2019-10-08,8.633688
43,Nordrhein_Westfalen,400.00,NaN,3.03,65.00,59425,10,False,1975.0,114832896,...,False,2,2,3,3.0,Unna_Kreis,Unna,Diese große Dachgeschosswohnung befindet sich ...,2020-02-01,NaN
44,Sachsen,266.00,396.00,0.43,58.95,2627,3,False,1987.0,84603557,...,True,1,3,2,4.0,Bautzen_Kreis,Radibor,Die Wohnung befindet sich in einem\nMehrfamili...,2019-10-08,6.717557
45,Berlin,820.00,1140.00,4.99,77.00,13591,10,False,NaN,115671495,...,False,6,3,3,NaN,Berlin,Staaken_Spandau,Diese attraktive EG-Wohnung kann ab sofort bez...,2020-02-01,14.805195
46,Hessen,2190.00,2190.00,5.92,96.00,60318,28,False,1900.0,110341073,...,False,9,4,4,1.0,Frankfurt_am_Main,Nordend_West,Diese Wohnung ist voll möbliert und nur auf Ze...,2019-05-10,22.812500
47,Sachsen_Anhalt,260.00,340.00,5.00,40.00,6132,8,False,1920.0,110876214,...,False,1,2,1,1.0,Halle_Saale,Radewell_Osendorf,"2 separate Zimmer, Bad und Küche mit Fenster s...",2019-05-10,8.500000
48,Schleswig_Holstein,870.00,1113.00,3.90,81.00,25379,2,True,2019.0,113054252,...,False,6,3,4,9.0,Steinburg_Kreis,Herzhorn,Das moderne Mehrfamilienhaus im Herzen von He...,2019-10-08,13.740741
49,Bayern,850.00,NaN,3.45,77.08,63743,11,False,2007.0,110536481,...,False,6,3,3,7.0,Aschaffenburg,Obernauer_Kolonie,LIEBHABER GESUCHT - STILVOLLE 3-ZIMMERWOHNUNG ...,2019-05-10,NaN

# 02. Merge rent data with state population data

In [11]:
# rename state column so it matches with merge column in the rent data
df_pop = df_pop.rename(columns={'state': 'regio1'})

In [12]:
df_pop.head()

,regio1,population,surface area,population density,space/person,people/apt,population trend,pop trend cat
0,Baden_Württemberg,11090990,35751,310,42.55,2.21,0.26,increase
1,Bayern,13113880,70552,186,44.28,2.15,0.35,increase
2,Berlin,3659468,892,4103,38.66,1.85,0.39,increase
3,Brandenburg,2521627,29486,86,40.76,2.00,-0.12,decrease
4,Bremen,681439,419,1626,40.81,1.92,0.11,increase

In [13]:
# merge
df_merge = df_rent.merge(df_pop, on = 'regio1', indicator = True)

In [14]:
df_merge.head()

,regio1,baseRent,totalRent,pricetrend,livingSpace,geo_plz,picturecount,newlyConst,yearConstructed,scoutId,...,date,price/unit,population,surface area,population density,space/person,people/apt,population trend,pop trend cat,_merge
0,Nordrhein_Westfalen,595.0,840.00,4.62,86.00,44269,6,False,1965.0,96107057,...,2019-05-10,9.767442,17935147,34098,526,41.41,2.12,-0.02,stable,both
1,Nordrhein_Westfalen,300.0,NaN,1.92,60.00,45888,7,False,1953.0,91383597,...,2019-10-08,NaN,17935147,34098,526,41.41,2.12,-0.02,stable,both
2,Nordrhein_Westfalen,950.0,1150.00,3.45,123.44,59065,3,False,1951.0,101730329,...,2019-10-08,9.316267,17935147,34098,526,41.41,2.12,-0.02,stable,both
3,Nordrhein_Westfalen,972.6,1320.65,3.76,87.00,44229,12,True,2018.0,92798563,...,2019-05-10,15.179885,17935147,34098,526,41.41,2.12,-0.02,stable,both
4,Nordrhein_Westfalen,329.0,NaN,3.12,65.00,47166,5,False,1914.0,111227157,...,2019-05-10,NaN,17935147,34098,526,41.41,2.12,-0.02,stable,both

In [15]:
# check merge flag
df_merge['_merge'].value_counts()

both          268772
left_only          0
right_only         0
Name: _merge, dtype: int64

In [16]:
# rearrange columns
df_merge = df_merge[['scoutId', 'regio1', 'baseRent', 'totalRent', 'pricetrend', 'livingSpace', 'geo_plz', 'picturecount', 'newlyConst', 'yearConstructed', 'firingTypes', 'heatingType', 'hasKitchen', 'cellar', 'condition', 'street', 'lift', 'typeOfFlat', 'noRooms', 'floor', 'balcony', 'garden',
'baseRentRange', 'noRoomsRange', 'livingSpaceRange', 'yearConstructedRange', 'regio2', 'regio3', 'description', 'date', 'population', 'population trend', 'pop trend cat', 'surface area', 'population density', 'space/person', 'people/apt', '_merge']]

In [17]:
# drop merge flag
df_merge = df_merge.drop(['_merge'], axis=1)

In [18]:
df_merge.head()

,scoutId,regio1,baseRent,totalRent,pricetrend,livingSpace,geo_plz,picturecount,newlyConst,yearConstructed,...,regio3,description,date,population,population trend,pop trend cat,surface area,population density,space/person,people/apt
0,96107057,Nordrhein_Westfalen,595.0,840.00,4.62,86.00,44269,6,False,1965.0,...,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,2019-05-10,17935147,-0.02,stable,34098,526,41.41,2.12
1,91383597,Nordrhein_Westfalen,300.0,NaN,1.92,60.00,45888,7,False,1953.0,...,Bulmke_Hüllen,Sie sind auf der Suche nach einer gepflegten u...,2019-10-08,17935147,-0.02,stable,34098,526,41.41,2.12
2,101730329,Nordrhein_Westfalen,950.0,1150.00,3.45,123.44,59065,3,False,1951.0,...,Mitte,Die angebotene Wohnfläche befindet sich im dri...,2019-10-08,17935147,-0.02,stable,34098,526,41.41,2.12
3,92798563,Nordrhein_Westfalen,972.6,1320.65,3.76,87.00,44229,12,True,2018.0,...,Kirchhörde,Der attraktive Neubau mit 10 Wohnungen liegt i...,2019-05-10,17935147,-0.02,stable,34098,526,41.41,2.12
4,111227157,Nordrhein_Westfalen,329.0,NaN,3.12,65.00,47166,5,False,1914.0,...,Obermarxloh,Gepflegtes Mehrfamilienhaus in Duisburg-Oberm...,2019-05-10,17935147,-0.02,stable,34098,526,41.41,2.12

In [19]:
# rename columns to match with naming convention in rent data
df_merge = df_merge.rename(columns={'geo_plz': 'plz', 'population trend': 'populationTrend', 'pop trend cat': 'popTrendCat', 'surface area': 'surfaceArea', 'population density': 'populationDensity'})

In [20]:
df_merge.head()

,scoutId,regio1,baseRent,totalRent,pricetrend,livingSpace,plz,picturecount,newlyConst,yearConstructed,...,regio3,description,date,population,populationTrend,popTrendCat,surfaceArea,populationDensity,space/person,people/apt
0,96107057,Nordrhein_Westfalen,595.0,840.00,4.62,86.00,44269,6,False,1965.0,...,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,2019-05-10,17935147,-0.02,stable,34098,526,41.41,2.12
1,91383597,Nordrhein_Westfalen,300.0,NaN,1.92,60.00,45888,7,False,1953.0,...,Bulmke_Hüllen,Sie sind auf der Suche nach einer gepflegten u...,2019-10-08,17935147,-0.02,stable,34098,526,41.41,2.12
2,101730329,Nordrhein_Westfalen,950.0,1150.00,3.45,123.44,59065,3,False,1951.0,...,Mitte,Die angebotene Wohnfläche befindet sich im dri...,2019-10-08,17935147,-0.02,stable,34098,526,41.41,2.12
3,92798563,Nordrhein_Westfalen,972.6,1320.65,3.76,87.00,44229,12,True,2018.0,...,Kirchhörde,Der attraktive Neubau mit 10 Wohnungen liegt i...,2019-05-10,17935147,-0.02,stable,34098,526,41.41,2.12
4,111227157,Nordrhein_Westfalen,329.0,NaN,3.12,65.00,47166,5,False,1914.0,...,Obermarxloh,Gepflegtes Mehrfamilienhaus in Duisburg-Oberm...,2019-05-10,17935147,-0.02,stable,34098,526,41.41,2.12

In [21]:
df_merge.to_csv(r'C:\Users\jacym\Desktop\Career Foundry projects\german rent\02 Data\cleaned data\rent_pop_merged.csv', encoding = 'utf8', index=False)

# 03. Merge rent/state pop data with district pop data

In [22]:
df_merge2 = df_merge.merge(df_district_pop, on = 'regio2', indicator = True)

In [23]:
df_merge2.head()

,scoutId,regio1,baseRent,totalRent,pricetrend,livingSpace,plz,picturecount,newlyConst,yearConstructed,...,population,populationTrend,popTrendCat,surfaceArea,populationDensity,space/person,people/apt,districtPopTrend,districtPop,_merge
0,96107057,Nordrhein_Westfalen,595.0,840.00,4.62,86.00,44269,6,False,1965.0,...,17935147,-0.02,stable,34098,526,41.41,2.12,0.33,587010,both
1,92798563,Nordrhein_Westfalen,972.6,1320.65,3.76,87.00,44229,12,True,2018.0,...,17935147,-0.02,stable,34098,526,41.41,2.12,0.33,587010,both
2,114894763,Nordrhein_Westfalen,396.8,493.80,4.10,62.00,44137,0,False,1958.0,...,17935147,-0.02,stable,34098,526,41.41,2.12,0.33,587010,both
3,90046012,Nordrhein_Westfalen,310.0,460.00,3.28,55.00,44329,14,False,1930.0,...,17935147,-0.02,stable,34098,526,41.41,2.12,0.33,587010,both
4,87928570,Nordrhein_Westfalen,301.0,NaN,4.41,30.07,44137,31,False,1979.0,...,17935147,-0.02,stable,34098,526,41.41,2.12,0.33,587010,both

In [24]:
# drop merge flag column
df_merge2 = df_merge2.drop(['_merge'], axis=1)

In [25]:
df_merge2.columns

Index(['scoutId', 'regio1', 'baseRent', 'totalRent', 'pricetrend',
       'livingSpace', 'plz', 'picturecount', 'newlyConst', 'yearConstructed',
       'firingTypes', 'heatingType', 'hasKitchen', 'cellar', 'condition',
       'street', 'lift', 'typeOfFlat', 'noRooms', 'floor', 'balcony', 'garden',
       'baseRentRange', 'noRoomsRange', 'livingSpaceRange',
       'yearConstructedRange', 'regio2', 'regio3', 'description', 'date',
       'population', 'populationTrend', 'popTrendCat', 'surfaceArea',
       'populationDensity', 'space/person', 'people/apt', 'districtPopTrend',
       'districtPop'],
      dtype='object')

In [26]:
# export merged data
df_merge2.to_csv(r'C:\Users\jacym\Desktop\Career Foundry projects\german rent\02 Data\cleaned data\rent_district_pop_merged.csv', encoding = 'utf8', index=False)